-- Supabase Database Services on roland1
-- Migration: 20260912_init_detections.sql
-- Initializes detection tables, indices, views, and storage bucket for RatWatch appliance

-- 1. Create detections table
CREATE TABLE IF NOT EXISTS public.detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT,
    frame_index INTEGER DEFAULT 1,
    timestamp TEXT NOT NULL,
    formatted_time TEXT NOT NULL,
    filename TEXT NOT NULL,
    confidence REAL NOT NULL,
    description TEXT,
    object_type TEXT DEFAULT 'rat',
    label TEXT DEFAULT 'Rat',
    battery_percentage INTEGER,
    device_name TEXT DEFAULT 'Roland 1 Camera',
    bounding_box TEXT,
    created_at DOUBLE PRECISION NOT NULL
);

-- 2. Indices for fast chronological queries and event session grouping
CREATE INDEX IF NOT EXISTS idx_detections_created_at ON public.detections (created_at);
CREATE INDEX IF NOT EXISTS idx_detections_event_id ON public.detections (event_id);
CREATE INDEX IF NOT EXISTS idx_detections_object_type ON public.detections (object_type);
CREATE INDEX IF NOT EXISTS idx_detections_label ON public.detections (label);

-- 3. Continuous sightings event summary view
CREATE OR REPLACE VIEW public.events_summary AS
SELECT 
    COALESCE(event_id, 'evt_' || id::text) AS session_id,
    object_type,
    label,
    device_name,
    MIN(created_at) AS start_ts,
    MAX(created_at) AS end_ts,
    MIN(formatted_time) AS formatted_start,
    MAX(formatted_time) AS formatted_end,
    MIN(timestamp) AS start_iso,
    MAX(timestamp) AS end_iso,
    MAX(confidence) AS max_confidence,
    COUNT(*) AS frame_count,
    MIN(id) AS first_frame_id,
    MAX(id) AS latest_frame_id
FROM public.detections
GROUP BY session_id, object_type, label, device_name;

-- 4. Enable Row-Level Security and grant access
ALTER TABLE public.detections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on detections"
    ON public.detections FOR SELECT
    USING (true);

CREATE POLICY "Allow public insert on detections"
    ON public.detections FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow public update on detections"
    ON public.detections FOR UPDATE
    USING (true);

CREATE POLICY "Allow public delete on detections"
    ON public.detections FOR DELETE
    USING (true);

-- 5. Storage bucket initialization for detection image crops
DO $$
BEGIN
    INSERT INTO storage.buckets (id, name, public)
    VALUES ('detections', 'detections', true)
    ON CONFLICT (id) DO UPDATE SET public = true;
EXCEPTION
    WHEN undefined_table THEN
        -- storage schema not yet initialized in bare PostgreSQL
        NULL;
END $$;
